'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";
import { useSession } from "next-auth/react";
import LogOut from "@/components/navbar";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import SidebarStatus from "@/components/sidebarStatus";

const inter = Inter({ subsets: ['greek'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <body className={inter.className + ' bg-[#0f1e46] '}>
        <Provider >
          <div className="flex  ">
            <Sidebar />
            <SidebarStatus />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
