'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";
import { useSession } from "next-auth/react";
import LogOut from "@/components/navbar";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import SidebarStatus from "@/components/sidebarStatus";
import { useState } from "react";

const inter = Inter({ subsets: ['greek'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [idOfSelectedConv, setIdOfSelectedConv] = useState(0)
  const [option, setOption] = useState('chat')
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Provider >
          <div className="flex bg-[#0f1e46]  ">
            <Navbar />
            <Sidebar option={option} setOption={setOption} />
            <SidebarStatus option={option} idOfSelectedConv={idOfSelectedConv} setIdOfSelectedConv={setIdOfSelectedConv} />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
